language: python
python:
  - "2.7"
  - "3.6"
services:
  - docker
before_install:
  - docker run -it -d -p 5000:5000 codait/max-image-caption-generator
  - sleep 60
  - pip install -r requirements.txt
install:
  - python app.py &
  - sleep 90
before_script:
  - pip install -r requirements-test.txt
script:
  - flake8 -v
  - pytest tests/test.py