apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: image-caption-generator-web-app
spec:
  selector:
    matchLabels:
      app: image-caption-generator-web-app
  replicas: 1
  template:
    metadata:
      labels:
        app: image-caption-generator-web-app
    spec:
      containers:
      - name: image-caption-generator-web-app
        image: codait/max-image-caption-generator-web-app:latest
        command: ["python", "app.py", "--ml-endpoint=http://image-caption-generator:5000"]
        ports:
        - containerPort: 8088
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: image-caption-generator-web-app
  name: image-caption-generator-web-app
spec:
  ports:
    - port: 8088
  selector:
    app: image-caption-generator-web-app
  type: LoadBalancer