version: '2'
template:
  name: "Deploy to IBM Cloud: Image Caption Generator Web App"
  description: "After you click **Deploy**, the web app will be deployed to IBM Cloud.\n\nThe toolchain uses tools that are part of the Continuous Delivery service. If an instance of that service isn't already in the selected organization, when you click **Deploy**, it is automatically added with the free [Lite](/catalog/services/continuous-delivery/) plan selected."
  required:
    - build
    - repo
  info:
    git url: >-
      [https://github.com/IBM/MAX-Image-Caption-Generator-Web-App](https://github.com/IBM/MAX-Image-Caption-Generator-Web-App)
toolchain:
  name: 'MAX-Image-Caption-Generator-Web-App-{{timestamp}}'
  template:
    getting_started: "**Your app is being created! Quick start:** To watch the pipeline deploy your app, click **Delivery Pipeline**. After the app is deployed, you can see it running by clicking **View app**."

services:
  repo:
    service_id: hostedgit
    parameters:
      repo_name: '{{toolchain.name}}'
      repo_url: '{{repository}}'
      type: clone
      has_issues: false
  build:
    service_id: pipeline
    parameters:
      services:
        - repo
      name: '{{toolchain.name}}'
      ui-pipeline: true
      configuration:
        content:
          $text: pipeline.yml
        env:
          REPO: repo
          BRANCH: '{{branch}}'
          CF_APP: '{{form.pipeline.parameters.app-name}}'
          CF_SPACE: '{{form.pipeline.parameters.dev-space}}'
          CF_ORGANIZATION: '{{form.pipeline.parameters.dev-organization}}'
          CF_REGION_ID: '{{form.pipeline.parameters.dev-region}}'
          ML_ENDPOINT: '{{form.pipeline.parameters.dev-ml-endpoint}}'
        execute: true
form:
  pipeline:
    parameters:
      dev-region: '{{region}}'
      dev-organization: '{{organization}}'
      dev-space: dev
      app-name: '{{services.repo.parameters.repo_name}}'
      dev-ml-endpoint: ''
    schema:
      $ref: deploy.json